import '../styles/globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Image from 'next/image';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Nasa pics',
	description: 'Generated by Mario',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang='en'>
			<body className={` ${inter.className}`}>
				<header className='p-4 bg-black w-full flex justify-between items-center border-b-2 border-purple-600 opacity-50'>
					<div>
						<Image src='/favicon-192.png' height={50} width={50} alt='Mario lafuente' />
					</div>
				</header>
				<main className='min-h-screen bg-black w-full   text-white z-10 text-sm lg:flex'>{children}</main>
				<footer className='p-4 bg-slate-800  w-full flex  items-center border-t-2 border-purple-600'>
					<div className='flex justify-between w-full items-center'>
						<div>
							<Image src='/favicon-192.png' height={70} width={70} alt='Mario lafuente' />
						</div>
						<div className='text-sm w-5/12 text-gray-600'>
							Discover the wonders of space and the cosmos with the NASA API, meticulously crafted by Mario LaFuente.{'\n'}
							Get Started: Begin your journey into the cosmos by searching for images, browsing Mars rover photos, or diving into the depths of space. The universe is at your fingertips!
						</div>
					</div>
				</footer>
			</body>
		</html>
	);
}
