import '../styles/globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Nasa pics',
	description: 'Generated by Mario',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang='en'>
			<body className={inter.className}>
				<header className='p-4 bg-slate-800 h-20 w-full flex justify-between items-center'>HEADER</header>
				<main className='p-4 bg-white w-full  text-black z-10 text-sm lg:flex'>{children}</main>
				<footer className='p-4 bg-slate-800 h-20 w-full flex justify-between items-center'>footer</footer>
			</body>
		</html>
	);
}
